export const API_BASE_URL = 'http://localhost:5000';

export const API_URLS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register'
  },
  SCHOOL: {
    GET_CLASS: '/classes',
    GET_CLASSES: '/classes',
    CREATE_CLASS: '/classes',
    EDIT_CLASS: '/classes',
  },
  STUDENT: {
    CREATE: '/students'
  },
  STUDENTS: {
    GET_STUDENT: '/students',
    GET_STUDENTS: '/users/students',
    CREATE_STUDENT: '/users/students',
    UPDATE_STUDENT: '/users/students/:studentId',
    DELETE_STUDENT: '/users/students/:studentId',
    GET_STUDENTS_BY_CLASS: '/students/by-class/:classId',
  },
  COURSES: {
    CREATE_COURSE: '/subjects-courses/courses',
    GET_COURSE: '/courses',
    GET_COURSES: '/courses',
    UPDATE_COURSE: '/courses',
    DELETE_COURSE: '',
    GET_COURSE_BY_ID: ''
  },
  TEACHERS: {
    GET_TEACHER: '/users/teachers',
    GET_TEACHERS: '/users/teachers',
    CREATE_TEACHER: '/teachers/',
    UPDATE_TEACHER: '/users/teachers/:userId',
    DELETE_TEACHER: '/users/teachers/:userId',
    DEACTIVATE_TEACHER: '/users/teachers/:userId',
    REGISTER_TEACHER: '/teachers/:userId'
  },
  NOTIFICATION: {
    CREATE_ANNOUNCEMENT: '/notifications/announcements',
    GET_ANNOUNCEMENTS_BY_SENDER: '/notifications/announcements/sender/:senderId?page=:page&limit=:limit',
  },
  FILES: {
    UPLOAD_IMAGE: '/upload/image'
  },
  ACADEMIC: {
    CREATE_ACADEMIC_YEAR: '/academic-year-term/academic-year',
    GET_ACADEMIC_YEARS: '/academic-year-term/academic-year/school',
    CREATE_TERM: '/academic-year-term/term',
    GET_TERMS: '/academic-year-term/term/school',
    SET_CURRENT_TERM: '/academic-year-term/term/:termId/set-current',
  },
  TIMETABLE: {
    CREATE_TIMETABLE_ENTRY: '/timetable/entry',
    GET_TIMETABLE: '/timetable?page=:page&limit=:limit',
    GET_TIMETABLE_BY_DAY: '/timetable/day/:day',
    UPDATE_TIMETABLE_ENTRY: '/timetable/entry/:entryId',
    DELETE_TIMETABLE_ENTRY: '/timetable/entry/:entryId'
  },
  COMPLAINTS: {
    CREATE_COMPLAINT: '/complaints',
    GET_COMPLAINTS: '/complaints/by-user',
    GET_COMPLAINT_BY_TICKET: '/complaints/:ticket'
  }
};

export const API_ENDPOINTS = {
  BASE_URL: API_BASE_URL,
  LOGIN: `${API_BASE_URL}${API_URLS.AUTH.LOGIN}`,
  INTROSPECT: `${API_BASE_URL}/auth/introspect`,
  LOGOUT: `${API_BASE_URL}/auth/logout`,
  REGISTER: `${API_BASE_URL}${API_URLS.AUTH.REGISTER}`,
  GET_CLASS: `${API_BASE_URL}${API_URLS.SCHOOL.GET_CLASS}`,
  GET_CLASSES: `${API_BASE_URL}${API_URLS.SCHOOL.GET_CLASSES}`,
  CREATE_CLASS: `${API_BASE_URL}${API_URLS.SCHOOL.EDIT_CLASS}`,
  EDIT_CLASS: `${API_BASE_URL}${API_URLS.SCHOOL.CREATE_CLASS}`,
  CREATE_ANNOUNCEMENT: `${API_BASE_URL}${API_URLS.NOTIFICATION.CREATE_ANNOUNCEMENT}`,
  CREATE_STUDENT: `${API_BASE_URL}${API_URLS.STUDENT.CREATE}`,
  UPLOAD_IMAGE: `${API_BASE_URL}${API_URLS.FILES.UPLOAD_IMAGE}`,
  GET_ANNOUNCEMENTS_BY_SENDER: `${API_BASE_URL}${API_URLS.NOTIFICATION.GET_ANNOUNCEMENTS_BY_SENDER}`,
  CREATE_ACADEMIC_YEAR: `${API_BASE_URL}${API_URLS.ACADEMIC.CREATE_ACADEMIC_YEAR}`,
  GET_ACADEMIC_YEARS: `${API_BASE_URL}${API_URLS.ACADEMIC.GET_ACADEMIC_YEARS}`,
  CREATE_TERM: `${API_BASE_URL}${API_URLS.ACADEMIC.CREATE_TERM}`,
  GET_TERMS: `${API_BASE_URL}${API_URLS.ACADEMIC.GET_TERMS}`,
  SET_CURRENT_TERM: `${API_BASE_URL}${API_URLS.ACADEMIC.SET_CURRENT_TERM}`,
  CREATE_TIMETABLE_ENTRY: `${API_BASE_URL}${API_URLS.TIMETABLE.CREATE_TIMETABLE_ENTRY}`,
  GET_TIMETABLE: `${API_BASE_URL}${API_URLS.TIMETABLE.GET_TIMETABLE}`,
  GET_TIMETABLE_BY_DAY: `${API_BASE_URL}${API_URLS.TIMETABLE.GET_TIMETABLE_BY_DAY}`,
  UPDATE_TIMETABLE_ENTRY: `${API_BASE_URL}${API_URLS.TIMETABLE.UPDATE_TIMETABLE_ENTRY}`,
  DELETE_TIMETABLE_ENTRY: `${API_BASE_URL}${API_URLS.TIMETABLE.DELETE_TIMETABLE_ENTRY}`,
  CREATE_COMPLAINT: `${API_BASE_URL}${API_URLS.COMPLAINTS.CREATE_COMPLAINT}`,
  GET_COMPLAINTS: `${API_BASE_URL}${API_URLS.COMPLAINTS.GET_COMPLAINTS}`,
  GET_COMPLAINT_BY_TICKET: `${API_BASE_URL}${API_URLS.COMPLAINTS.GET_COMPLAINT_BY_TICKET}`,
  GET_STUDENTS: `${API_BASE_URL}${API_URLS.STUDENTS.GET_STUDENTS}`,
  CREATE_STUDENT_NEW: `${API_BASE_URL}${API_URLS.STUDENTS.CREATE_STUDENT}`,
  UPDATE_STUDENT: `${API_BASE_URL}${API_URLS.STUDENTS.UPDATE_STUDENT}`,
  DELETE_STUDENT: `${API_BASE_URL}${API_URLS.STUDENTS.DELETE_STUDENT}`,
  
  CREATE_TEACHER: `${API_BASE_URL}${API_URLS.TEACHERS.CREATE_TEACHER}`,
  GET_TEACHER: `${API_BASE_URL}${API_URLS.TEACHERS.GET_TEACHER}`,
  GET_TEACHERS: `${API_BASE_URL}${API_URLS.TEACHERS.GET_TEACHERS}`,
  REGISTER_TEACHER: `${API_BASE_URL}${API_URLS.TEACHERS.REGISTER_TEACHER}`,
  UPDATE_TEACHER: `${API_BASE_URL}${API_URLS.TEACHERS.UPDATE_TEACHER}`,
  DEACTIVATE_TEACHER: `${API_BASE_URL}${API_URLS.TEACHERS.DEACTIVATE_TEACHER}`,
  GET_STUDENTS_BY_CLASS: `${API_BASE_URL}${API_URLS.STUDENTS.GET_STUDENTS_BY_CLASS}`,
  GET_STUDENT: `${API_BASE_URL}${API_URLS.STUDENTS.GET_STUDENT}`,


  CREATE_COURSE: `${API_BASE_URL}${API_URLS.COURSES.CREATE_COURSE}`,
  GET_COURSES: `${API_BASE_URL}${API_URLS.COURSES.GET_COURSES}`,
  UPDATE_COURSE: `${API_BASE_URL}${API_URLS.COURSES.UPDATE_COURSE}`,
  DELETE_COURSE: `${API_BASE_URL}${API_URLS.COURSES.DELETE_COURSE}`,
  GET_COURSE_BY_ID: `${API_BASE_URL}${API_URLS.COURSES.GET_COURSE_BY_ID}`,


} as const;