export const API_BASE_URL = 'http://localhost:5000';

export const API_URLS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register'
  },
  SCHOOL: {
    GET_CLASS: '/classes',
    GET_CLASSES: '/classes',
    CREATE_CLASS: '/classes',
    EDIT_CLASS: '/classes',
  },
  STUDENT: {
    CREATE: '/students'
  },
  NOTIFICATION: {
    CREATE_ANNOUNCEMENT: '/notifications/announcements',
    GET_ANNOUNCEMENTS_BY_SENDER: '/notifications/announcements/sender/:senderId?page=:page&limit=:limit',
  },
  FILES: {
    UPLOAD_IMAGE: '/upload/image'
  },
  ACADEMIC: {
    CREATE_ACADEMIC_YEAR: '/academic-year-term/academic-year',
    GET_ACADEMIC_YEARS: '/academic-year-term/academic-year/school',
    CREATE_TERM: '/academic-year-term/term',
    GET_TERMS: '/academic-year-term/term/school',
    SET_CURRENT_TERM: '/academic-year-term/term/:termId/set-current',
  },
  TIMETABLE: {
    CREATE_TIMETABLE_ENTRY: '/timetable/entry',
    GET_TIMETABLE: '/timetable?page=:page&limit=:limit',
    GET_TIMETABLE_BY_DAY: '/timetable/day/:day',
    UPDATE_TIMETABLE_ENTRY: '/timetable/entry/:entryId',
    DELETE_TIMETABLE_ENTRY: '/timetable/entry/:entryId'
  },
  COMPLAINTS: {
    CREATE_COMPLAINT: '/complaints',
    GET_COMPLAINTS: '/complaints',
    GET_COMPLAINT_BY_TICKET: '/complaints/:ticket'
  }
};

export const API_ENDPOINTS = {
  BASE_URL: API_BASE_URL,
  LOGIN: `${API_BASE_URL}${API_URLS.AUTH.LOGIN}`,
  INTROSPECT: `${API_BASE_URL}/auth/introspect`,
  LOGOUT: `${API_BASE_URL}/auth/logout`,
  REGISTER: `${API_BASE_URL}${API_URLS.AUTH.REGISTER}`,
  GET_CLASS: `${API_BASE_URL}${API_URLS.SCHOOL.GET_CLASS}`,
  GET_CLASSES: `${API_BASE_URL}${API_URLS.SCHOOL.GET_CLASSES}`,
  CREATE_CLASS: `${API_BASE_URL}${API_URLS.SCHOOL.EDIT_CLASS}`,
  EDIT_CLASS: `${API_BASE_URL}${API_URLS.SCHOOL.CREATE_CLASS}`,
  CREATE_ANNOUNCEMENT: `${API_BASE_URL}${API_URLS.NOTIFICATION.CREATE_ANNOUNCEMENT}`,
  CREATE_STUDENT: `${API_BASE_URL}${API_URLS.STUDENT.CREATE}`,
  UPLOAD_IMAGE: `${API_BASE_URL}${API_URLS.FILES.UPLOAD_IMAGE}`,
  GET_ANNOUNCEMENTS_BY_SENDER: `${API_BASE_URL}${API_URLS.NOTIFICATION.GET_ANNOUNCEMENTS_BY_SENDER}`,
  CREATE_ACADEMIC_YEAR: `${API_BASE_URL}${API_URLS.ACADEMIC.CREATE_ACADEMIC_YEAR}`,
  GET_ACADEMIC_YEARS: `${API_BASE_URL}${API_URLS.ACADEMIC.GET_ACADEMIC_YEARS}`,
  CREATE_TERM: `${API_BASE_URL}${API_URLS.ACADEMIC.CREATE_TERM}`,
  GET_TERMS: `${API_BASE_URL}${API_URLS.ACADEMIC.GET_TERMS}`,
  SET_CURRENT_TERM: `${API_BASE_URL}${API_URLS.ACADEMIC.SET_CURRENT_TERM}`,
  CREATE_TIMETABLE_ENTRY: `${API_BASE_URL}${API_URLS.TIMETABLE.CREATE_TIMETABLE_ENTRY}`,
  GET_TIMETABLE: `${API_BASE_URL}${API_URLS.TIMETABLE.GET_TIMETABLE}`,
  GET_TIMETABLE_BY_DAY: `${API_BASE_URL}${API_URLS.TIMETABLE.GET_TIMETABLE_BY_DAY}`,
  UPDATE_TIMETABLE_ENTRY: `${API_BASE_URL}${API_URLS.TIMETABLE.UPDATE_TIMETABLE_ENTRY}`,
  DELETE_TIMETABLE_ENTRY: `${API_BASE_URL}${API_URLS.TIMETABLE.DELETE_TIMETABLE_ENTRY}`,
  CREATE_COMPLAINT: `${API_BASE_URL}${API_URLS.COMPLAINTS.CREATE_COMPLAINT}`,
  GET_COMPLAINTS: `${API_BASE_URL}${API_URLS.COMPLAINTS.GET_COMPLAINTS}`,
  GET_COMPLAINT_BY_TICKET: `${API_BASE_URL}${API_URLS.COMPLAINTS.GET_COMPLAINT_BY_TICKET}`
} as const;